# Cloud Build configuration for Unified Space Exploration Agent
# Builds and deploys both frontend and backend as a single Cloud Run service

steps:
  # Build the unified Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '--tag=gcr.io/$PROJECT_ID/space-agent-unified:$BUILD_ID'
      - '--tag=gcr.io/$PROJECT_ID/space-agent-unified:latest'
      - '--file=Dockerfile'
      - '.'
    id: 'build-unified'

  # Push image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'gcr.io/$PROJECT_ID/space-agent-unified:$BUILD_ID'
    id: 'push-unified'
    waitFor: ['build-unified']

  # Deploy to Cloud Run as a single service
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - space-agent-unified
      - '--image=gcr.io/$PROJECT_ID/space-agent-unified:$BUILD_ID'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=2Gi'
      - '--cpu=1'
      - '--concurrency=80'
      - '--max-instances=10'
      - '--set-env-vars=NODE_ENV=production'
    id: 'deploy-unified'
    waitFor: ['push-unified']

# Timeout for the entire build process
timeout: '1200s'

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8' 